zuul:
  routes:
    warehouse:
      path: /api/warehouse/**
      url: http://localhost:8437/api/warehouse
    orders:
      path: /api/orders/**
      url: http://localhost:8038/api/orders
    payment:
      path: /api/payment/**
      url: http://localhost:8037/api/payment
ribbon:
  eureka:
    enabled: false

server:
  port: 8099
